# Generated by Django 5.2.17 on 2026-09-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Medicine', 'Medicine'), ('Cosmetics', 'Cosmetics'), ('Cleaning', 'Cleaning'), ('Personal Care', 'Personal Care'), ('Other', 'Other')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('storage_location', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
